ekf_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    odometry0: /odometry/wheel
    odometry0_config: [true,  true,  false,
                       false, false, true,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]
    odometry0_differential: false
    odometry0_relative: false

    odometry1: /odometry/imu
    odometry1_config: [false, false, false,
                       true,  true,  true,
                       false, false, false,
                       false, false, true,
                       false, false, false]
    odometry1_differential: false
    odometry1_relative: false
