scan_to_scan_filter_chain:
  ros__parameters:
    use_sensor_data_qos: true
    filter1:
      name: laser_scan_box
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.309
        upper_angle: 1.309
        target_frame: laser
