# config/slam_config.yaml
slam_toolbox:
  use_sim_time: false
  odom_frame: 'odom'
  map_frame: 'map'
  base_frame: 'base_footprint'
  scan_topic: '/scan'
  queue_size: 10
  map_update_interval: 0.5

lidar_params:
  channel_type: 'serial'
  serial_port: '/dev/ttyUSB0'
  serial_baudrate: 115200
  frame_id: 'laser'
  inverted: false
  angle_compensate: true
  scan_mode: 'Standard'
